[package]
name = "notify"
version = "5.1.0"
rust-version = "1.56"
description = "Cross-platform filesystem notification library"
documentation = "https://docs.rs/notify"
homepage = "https://github.com/notify-rs/notify"
repository = "https://github.com/notify-rs/notify.git"
readme = "../README.md"
license = "CC0-1.0 OR Artistic-2.0"
keywords = ["events", "filesystem", "notify", "watch"]
categories = ["filesystem"]
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Daniel Faust <hessijames@gmail.com>"
]

edition = "2021"

[dependencies]
bitflags = "1.0.4"
crossbeam-channel = { version = "0.5.0", optional = true }
filetime = "0.2.6"
libc = "0.2.4"
serde = { version = "1.0.89", features = ["derive"], optional = true }
walkdir = "2.2.2"

[target.'cfg(any(target_os="linux", target_os="android"))'.dependencies]
inotify = { version = "0.9", default-features = false }
mio = { version = "0.8", features = ["os-ext"] }

[target.'cfg(target_os="macos