name: CI

on:
  push:
    branches:
      # test branches
      - 'try-**'

      # main branches
      - main
      - next
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  ci:
    strategy:
      matrix:
        version:
          - 1.56.0 # MSRV
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: setup toolchain
        # `--no-self-update` is needed due to a permission issue on the GHA env.
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.version }} --no-self-update
          rustup override set ${{ matrix.version }}

      - name: check build serde,macos_kqueue for examples
        if: matrix.version != '1.56.0' && matrix.os == 'macos-la