name: CI

on:
  push:
    branches:
      # test branches
      - 'try-**'

      # main branches
      - main
      - next
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  ci:
    strategy:
      matrix:
        version:
          - 1.56.0 # MSRV
          - stable
          - n