name: CI

on:
  push:
    branches:
      # test branches
      - 'try-**'

      # main branches
      - main
      - next
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  ci:
    strategy:
      matrix:
        version:
          - 1.56.0 # MSRV
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: setup toolchain
        # `--no-self-update` is needed due to a permission issue on the GHA env.
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.version }} --no-self-update
          rustup override set ${{ matrix.version }}

      - name: check build serde,macos_kqueue for examples
        if: matrix.version != '1.56.0' && matrix.os == 'macos-latest'
        run: cargo check -p notify --features=serde,macos_kqueue --examples

      - name: check build serde,macos_kqueue
        if: matrix.version == '1.56.0' && matrix.os == 'macos-latest'
        run: cargo check -p notify --features=serde,macos_kqueue

      - name: check build serde for examples
        if: matrix.version != '1.56.0' && matrix.os != 'macos-latest'
        run: cargo check -p notify --features=serde --examples

      - name: check build serde
        if: matrix.version == '1.56.0' && matrix.os != 'macos-latest'
        run: cargo check --features=serde

      - name: check build without crossbeam/default features
        if: matrix.version == 'stable'
        run: cargo check -p notify --no-default-features --features=macos_fsevent
        # -p notify required for feature selection!

      - name: check build without crossbeam/default features on macos with kqueue
        if: matrix.version == 'stable' && matrix.os == 'macos-latest'
        run: cargo check -p notify --no-default-features --features=macos_kqueue
        # -p notify required for feature selection!

      - name: check notify debouncer mini features
        if: matrix.version == 'stable'
        run: cargo check -p notify-debouncer-mini --no-default-features
        # -p required for feature selection to actually work!

      - name: check build examples
        if: matrix.version == 'stable'
        run: cargo check --package examples --examples

      - name: test hot_